# Generated by Django 4.2.26 on 2025-11-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('duration', models.CharField(max_length=45)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('skill', models.CharField(max_length=45)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=45)),
                ('nextOfKinName', models.CharField(max_length=45)),
                ('nextOfKinRelationship', models.CharField(max_length=45)),
                ('nextOfKinNumber', models.CharField(max_length=45)),
                ('courseFee', models.FloatField()),
                ('batch', models.CharField(max_length=45)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courseregapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseFee', models.FloatField()),
                ('totalAmountPaid', models.FloatField()),
                ('balanceToPay', models.FloatField()),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymenttrack', to='courseregapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='courseregapp.student')),
            ],
        ),
    ]
