# Generated by Django 4.2.26 on 2026-01-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseregapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classStatus',
            field=models.CharField(default='Active', max_length=45),
        ),
        migrations.AddField(
            model_name='student',
            name='programType',
            field=models.CharField(default='Career Course', max_length=45),
        ),
        migrations.AlterField(
            model_name='payment',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courseregapp.student'),
        ),
    ]
